---

# task file for dgnest.opbeat

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install opbeat package dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_opbeat_package_dependencies
  when: _opbeat_package_dependencies is defined
  with_items: _opbeat_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_opbeat_package_dependencies.stdout_lines

- name: Install opbeat dependencies
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_opbeat_dependencies
  when: _opbeat_dependencies is defined
  with_items: _opbeat_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_opbeat_dependencies.stdout_lines