---

# task file for hadenlabs.opbeat

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes


- name: Install opbeat dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items: opbeat_packages
  tags:
    - opbeat
